=== DDOF/Projet_XML/master.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT master    (parcours+,intervenant+,unite+)>
<!ENTITY lum "Campus de luminy" >
<!ENTITY jer "Campus de Saint-jerome" >
<!ENTITY % riches "(#PCDATA | par | list | tab)*" >
<!ELEMENT tab (tr*)>
<!ELEMENT tr (th*) >
<!ELEMENT th (#PCDATA) >
<!ELEMENT list (li+)>
<!ELEMENT li (par*)>
<!ELEMENT par (#PCDATA | bold | i | a)*>
<!ELEMENT bold (#PCDATA)>
<!ELEMENT i (#PCDATA)>
<!ELEMENT a (#PCDATA)>
<!ELEMENT unite    (nom,credit,resume,plan,lieu,ref_intervenant)>
<!ATTLIST unite
    id ID #REQUIRED>
<!ELEMENT nom      (#PCDATA)>

<!ELEMENT id     (#PCDATA)>
<!ELEMENT credit     (#PCDATA)>
<!ELEMENT resume     %riches;>
<!ELEMENT plan     (#PCDATA)>
<!ELEMENT lieu     (#PCDATA)>
<!ELEMENT ref_intervenant     (#PCDATA)>
<!ATTLIST ref_intervenant
     ref IDREF #IMPLIED>
<!ELEMENT intervenant    (nom,mail)>
<!ATTLIST intervenant
     id ID #REQUIRED>


<!ELEMENT mail     (#PCDATA)>
<!ELEMENT parcours     (responsable+,nom,description,débouchés+,semestre+)>
<!ATTLIST parcours id ID #IMPLIED >
<!ELEMENT responsable     (#PCDATA)>
<!ELEMENT description     %riches;>
<!ELEMENT débouchés %riches;>
<!ELEMENT semestre     (role+)>
<!ATTLIST semestre numero (S1 | S2 | S3 | S4) "S1" >
<!ELEMENT role     (ref_unite+)>
<!ATTLIST role type (obligatoires|options) "obligatoires">
<!ELEMENT ref_unite     (#PCDATA)>
<!ATTLIST ref_unite
     ref IDREF #REQUIRED>

=== DDOF/Projet_XML/data/master.xml
<?xml version="1.0" encoding="iso-8859-1"?>
<!DOCTYPE master SYSTEM "master.dtd">
<master>
    <parcours>
        <responsable>Remi MORIN</responsable>
        <nom>Master 1</nom>
        <description> 
            L'objectif de cette première année est de donner les bases indispensables permettant, en deuxième année, de choisir une spécialisation dans un domaine précis. Sur les 60 crédits de cette première année, 15 crédits correspondent à des enseignements optionnels. Ces options permettent de construire un parcours adapté. Un choix entre stage ou projet encadré est également proposé au semestre de printemps.</description>
        <débouchés/>
        <semestre numero="S1">
            <role type="obligatoires">
                <ref_unite ref="ENSINAU1">Génie Logiciel (6 crédits)</ref_unite>
                <ref_unite ref="ENSINAU2">Complexité (6 crédits)</ref_unite>
                <ref_unite ref="ENSINAU3">Réseaux (6 crédits)</ref_unite>
                <ref_unite ref="ENSINAU4">Programmation fonctionnelle (3 crédits)</ref_unite>
                <ref_unite ref="ENSINAU12">BDR : approfondissement (3 crédits)</ref_unite>            
            </role>
            <role type="options">
                <ref_unite ref="ENSINAU6">Programmation logique (3 crédits)</ref_unite>
                <ref_unite ref="ENSINAU7">Outils de l'internet (3 crédits)</ref_unite>
                <ref_unite ref="ENSINAU8">Système embarqué (3 crédits)</ref_unite>
                <ref_unite ref="ENSINAU9">Fondamentaux pour l'ingénierie des langues (3 crédits)</ref_unite>
                <ref_unite ref="ENSINBU10">Modèles à évènements discrets (3 crédits)</ref_unite>
                <ref_unite ref="ENSINBU13">Pratique de la cryptographie (3 crédits)</ref_unite>
            </role>
        </semestre>
        <semestre numero="S2">
            <role type="obligatoires">
                <ref_unite ref="ENSINBU1">Anglais (3 crédits)</ref_unite>
                <ref_unite ref="ENSINBU2">Communication (3 crédits)</ref_unite>
                <ref_unite ref="ENSINBU4">XML (3 crédits)</ref_unite>
                <ref_unite ref="ENSINBU5">Algorithmique et recherche opérationnelle (3 crédits)</ref_unite>
                <ref_unite ref="ENSINBU15">Programmation parallèle (3 crédits)</ref_unite>
            </role>
            <role>
                <ref_unite ref="ENSINBU6">Projet (6 crédits)</ref_unite>
                <ref_unite ref="ENSINAU7">Stage de deux mois (6 crédits)</ref_unite>
            </role>
            <role type="options">
                <ref_unite ref="ENSINBU8">Sémantique (3 crédits)</ref_unite>
                <ref_unite ref="ENSINBU9">Algorithmique distribuée (3 crédits)</ref_unite>
                <ref_unite ref="ENSINBU10">Intégration des systèmes d'information (3 crédits)</ref_unite>
                <ref_unite ref="ENSINBU11">Initiation à la fouille de données et à l'optimisation des SGBD (3 crédits)</ref_unite>
                <ref_unite ref="ENSINBU12">Intelligence artificielle (3 crédits)</ref_unite>
                <ref_unite ref="ENSINBU13">Algorithme à performance garantie (3 crédits)</ref_unite>
                <ref_unite ref="ENSINBU16">Introduction à l'apprentissage automatique (3 crédits)</ref_unite>
            </role>
        </semestre>
    </parcours>
    <parcours>
        <responsable>Omar BOUCELMA</responsable>
        <nom>Systèmes dinformations répartis</nom>
        <description>Le programme vise la formation de spécialistes dans des métiers à forte valeur ajoutée au travers des compétences acquises dans trois domaines clés de l&#8217;informatique : les technologies avancées du Web (services web, multimédia, etc.), les nouveaux modes de développement du logiciel (Cloud, Mobile, etc.) et les processus métiers de l&#8217;entreprise.</description>
        <débouchés>La spécialité SIR vise des métiers de l&#8217;informatique à forte valeur ajoutée grâce aux compétences acquises dans trois domaines clés : les technologies avancées du Web, les nouveaux modes de développement et de déploiement de solutions logicielles et les processus métiers de l&#8217;entreprise.
            
            Parmi les métiers visés on trouve :
            
            Architecte en Systèmes d&#8217;Information,
            Ingénieur Développement Logiciels,
            Ingénieur Intégration,
            Consultant ERP/BPM,
            Chef de projet.
        </débouchés>
        <semestre numero="S3">
            <role type="obligatoires">
                <ref_unite ref="ENSINCU60">Architectures réparties - JEE (6 crédits)</ref_unite>
                <ref_unite ref="ENSINCU64">Développement d'applications mobiles (3 crédits)</ref_unite>
                <ref_unite ref="ENSINCU65">Gestion de projet (3 crédits)</ref_unite>
                <ref_unite ref="ENSINCU68">Cloud computing (3 crédits)</ref_unite>
                <ref_unite ref="ENSINCU74">Introduction au Big Data (3 crédits)</ref_unite>
                <ref_unite ref="ENSINCU75">Business process (3 crédits)</ref_unite>
                <ref_unite ref="ENSISCU28">RI8 : Web services (3 crédits)</ref_unite>
                <ref_unite ref="ENSINCU27">Anglais 2 (3 crédits)</ref_unite>
                <ref_unite ref="ENSINCU28">Communication 2 (3 crédits)</ref_unite>
            </role>
        </semestre>
        <semestre numero="S4">
            <role type="obligatoires">
                <ref_unite ref="ENSINDU3">Projet industriel de mise en application (6 crédits)</ref_unite>
                <ref_unite ref="ENSINDU4">Stage en entreprise (24 crédits)</ref_unite>
            </role>
        </semestre>
        
    </parcours>
    <intervenant id="massat">
        <nom>Jean-Luc MASSAT</nom>
        
        <mail>jean-luc.massat@univ-amu.fr</mail>
    </intervenant>
    <intervenant id="olive">
        <nom>Frederic OLIVE</nom>
        
        <mail>frederic.olive@univ-amu.fr</mail>
    </intervenant>
    <intervenant id="godard">
        <nom>Emmanuel GODARD</nom>
        
        <mail>emmanuel.godard@univ-amu.fr</mail>
    </intervenant>
    <intervenant id="morin">
        <nom>Remi MORIN</nom>
        
        <mail>remi.morin@univ-amu.fr</mail>
    </intervenant>
    <intervenant id="sabatier">
        <nom>laude SABATIER</nom>
        
        <mail>claude.sabatier@univ-amu.fr</mail>
    </intervenant>
    <intervenant id="broche">
        <nom>Martine BROCHE</nom>
        
        <mail>martine.broche@univ-amu.fr</mail>
    </intervenant>
    <intervenant id="jamet">
        <nom>Line JAMET</nom>
        
        <mail>line.jakubiec@univ-amu.fr</mail>
    </intervenant>
    <intervenant id="estellon">
        <nom>Bertrand ESTELLON</nom>
        
        <mail>bertrand.estellon@univ-amu.fr</mail>
    </intervenant>
    <intervenant id="novelli">
        <nom>Noel NOVELLI</nom>
        
        <mail>noel.novelli@univ-amu.fr</mail>
    </intervenant>
    <intervenant id="creignou">
        <nom>Nadia CREIGNOU</nom>
        
        <mail>nadia.creignou@univ-amu.fr</mail>
    </intervenant>
    <unite id="ENSINAU1">
        <nom>Génie Logiciel</nom>
        <credit>6</credit>
        <resume>
            Processus logiciel
            Gestion de projet
            Spécification et conception (artefact : notation UML)
            Design patterns
        </resume>
        <plan/>
        <lieu>&lum;</lieu>
        <ref_intervenant ref="massat"/>
    </unite>
    <unite id="ENSINAU2">
        <nom>Complexité </nom>
        <credit>6</credit>
        <resume>
            Rappels sur les notions d'analyse de la complexité des algorithmes et des problèmes.
            Notion de problèmes (décision, recherche, dénombrement, énumération, optimisation). Bornes inférieures de complexité.
            Classes P et NP. Problèmes NP-complets.
            Méthodes de résolution des problèmes NP-Complets.
        </resume>
        <plan/>
        <lieu>&lum;</lieu>
        <ref_intervenant ref="olive"/>
    </unite>
    <unite id="ENSINAU3">
        <nom>Réseaux </nom>
        <credit>6</credit>
        <resume>
            Architecture en couches, standard OSI
            Couche physique
            Couche liaison de Données
            Réseau IP
            Algorithmes de routage, routage IP
            Protocole TCP/IP
            Couche Application : HTTP, SMTP, FTP, ...
            Bases des protocoles cryptographiques (terminologie, architecture à clef publique).
            Introduction à la Sécurité des réseaux.
        </resume>
        <plan/>
        <lieu>&lum;</lieu>
        <ref_intervenant ref="godard"/>
    </unite>
    <unite id="ENSINAU4">
        <nom>Programmation fonctionnelle</nom>
        <credit>3</credit>
        <resume>1- Introduction à la programmation fonctionnelle, sur l'exemple du langage
            
            OCaml
            
            Expressions, évaluation, types de base. Polymorphisme, ordre supérieur.
            
            Fonctions récursives, filtrage. Les diverses stratégies d'évaluation, application à la programmation d'un opérateur de point fixe.
            
            2- Les types
            
            Sommes, types récursifs, polymorphes. Arbres. Filtrage.
            
            3- Sémantique opérationnelle
            
            Liaisons, environnements, clôtures. Évaluation des fonctions récursives .
            
            4- Aspects impératifs
            
            Exceptions, entrées-sorties, séquencement, fichiers, références, tableaux, enregistrements.
            
            5- Implantation du filtrage en OCaml
            
            Termes formels, substitutions, filtrage.</resume>
        <plan/>
        <lieu>&lum;</lieu>
        <ref_intervenant ref="novelli"/>
    </unite>
    <unite id="ENSINAU12">
        <nom> BDR : approfondissement</nom>
        <credit>3</credit>
        <resume>nous sommes désolé, mais nous n'avons pas encore de résumé.</resume>
        <plan/>
        <lieu>&lum;</lieu>
